import type { Blueprint } from '@/types';

export const OFFICIAL_BLUEPRINTS: Blueprint[] = [
  // ── DEVELOPMENT ─────────────────────────────────────────────────────────────
  {
    id: 'mern-stack',
    name: 'MERN Stack App',
    description: 'Full-stack MongoDB, Express, React, Node.js application with architecture docs and API design.',
    icon: '🌐',
    color: '#60A5FA',
    category: 'Development',
    setupTime: '~3 min',
    audience: 'Full-stack teams',
    features: ['6 Kanban columns', '5 sprints', 'API & setup docs', 'JWT auth tasks', 'CI/CD tasks'],
    planningItems: [
      { title: 'Vision', content: '## Vision\nBuild a scalable full-stack web application using the MERN stack.', order: 0 },
      { title: 'Architecture Notes', content: '## Architecture\n- **Frontend**: React + Vite\n- **Backend**: Node.js + Express\n- **Database**: MongoDB\n- **Auth**: JWT', order: 1 },
      { title: 'API Design', content: '## API Endpoints\n- `GET /api/users`\n- `POST /api/auth/login`\n- `POST /api/auth/register`', order: 2 },
    ],
    sprintNames: ['Setup & Architecture', 'Backend API', 'Frontend UI', 'Integration & Testing', 'Deployment'],
    labels: ['frontend', 'backend', 'api', 'database', 'auth', 'ui', 'testing', 'deployment'],
    defaultDocs: [
      { title: 'Project Setup Guide', content: '# Project Setup\n\n## Prerequisites\n- Node.js 18+\n- MongoDB\n\n## Installation\n```bash\nnpm install\nnpm run dev\n```' },
      { title: 'API Documentation', content: '# API Docs\n\n## Auth\nAll protected routes require `Authorization: Bearer <token>`.' },
    ],
    sampleTasks: [
      { title: 'Initialize Express server', description: 'Set up Node.js + Express with middleware', status: 'backlog', priority: 'high', labels: ['backend'], storyPoints: 3, acceptanceCriteria: 'Server runs on port 5000', assignee: '', isFavorite: false },
      { title: 'Set up MongoDB connection', description: 'Configure Mongoose and database connection', status: 'backlog', priority: 'high', labels: ['backend', 'database'], storyPoints: 2, acceptanceCriteria: 'DB connects successfully', assignee: '', isFavorite: false },
      { title: 'Create React app with Vite', description: 'Initialize frontend with React + Vite', status: 'backlog', priority: 'high', labels: ['frontend'], storyPoints: 2, acceptanceCriteria: 'App renders without errors', assignee: '', isFavorite: false },
      { title: 'JWT Authentication middleware', description: 'Implement login, register, token validation', status: 'backlog', priority: 'critical', labels: ['backend', 'auth'], storyPoints: 5, acceptanceCriteria: 'Users can register/login with tokens', assignee: '', isFavorite: false },
      { title: 'Responsive dashboard UI', description: 'Build main dashboard with data tables', status: 'backlog', priority: 'medium', labels: ['frontend', 'ui'], storyPoints: 5, acceptanceCriteria: 'Dashboard renders data from API', assignee: '', isFavorite: false },
      { title: 'Docker + CI/CD pipeline', description: 'Containerize app and add GitHub Actions', status: 'backlog', priority: 'medium', labels: ['deployment'], storyPoints: 5, acceptanceCriteria: 'App deploys on push to main', assignee: '', isFavorite: false },
    ],
    defaultSnippets: [
      { title: 'Express App Entry', language: 'javascript', description: 'Basic Express server bootstrap', tags: ['backend', 'server'], code: `const express = require('express');\nconst cors = require('cors');\nconst app = express();\n\napp.use(cors());\napp.use(express.json());\n\napp.listen(5000, () => console.log('Server running on port 5000'));` },
      { title: 'Mongoose Connect', language: 'javascript', description: 'MongoDB connection helper', tags: ['database', 'mongodb'], code: `const mongoose = require('mongoose');\n\nexport async function connectDB() {\n  await mongoose.connect(process.env.MONGO_URI);\n  console.log('MongoDB connected');\n}` },
    ],
  },
  {
    id: 'react-app',
    name: 'React SPA',
    description: 'Modern React single-page application with component library, routing, and state management.',
    icon: '⚛️',
    color: '#38BDF8',
    category: 'Development',
    setupTime: '~2 min',
    audience: 'Frontend developers',
    features: ['Component library setup', '3 sprints', 'State management docs', 'Testing tasks'],
    planningItems: [
      { title: 'Vision', content: '## Vision\nBuild a fast, modern React SPA.', order: 0 },
      { title: 'Component Architecture', content: '## Components\n- Atoms\n- Molecules\n- Organisms\n- Pages', order: 1 },
    ],
    sprintNames: ['Foundation & Routing', 'Core Features', 'Testing & Polish'],
    labels: ['react', 'ui', 'components', 'state', 'testing', 'a11y'],
    defaultDocs: [
      { title: 'Component Library', content: '# Component Library\n\nAll shared UI components live in `src/components/`.' },
      { title: 'State Management Guide', content: '# State Management\n\nUsing Zustand for global state.' },
    ],
    sampleTasks: [
      { title: 'Set up routing with React Router', status: 'backlog', priority: 'high', labels: ['react'], storyPoints: 2, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Design token system (CSS variables)', status: 'backlog', priority: 'high', labels: ['ui'], storyPoints: 3, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Build navigation layout', status: 'backlog', priority: 'medium', labels: ['ui', 'components'], storyPoints: 3, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Set up Vitest unit tests', status: 'backlog', priority: 'medium', labels: ['testing'], storyPoints: 2, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
    ],
    defaultSnippets: [
      { title: 'useLocalStorage Hook', language: 'typescript', description: 'Sync state to localStorage', tags: ['hooks', 'state'], code: `import { useState } from 'react';\n\nexport function useLocalStorage<T>(key: string, initial: T) {\n  const [value, setValue] = useState<T>(() => {\n    try { return JSON.parse(localStorage.getItem(key)!) ?? initial; }\n    catch { return initial; }\n  });\n  const set = (v: T) => { setValue(v); localStorage.setItem(key, JSON.stringify(v)); };\n  return [value, set] as const;\n}` },
    ],
  },
  {
    id: 'nextjs-saas',
    name: 'Next.js SaaS',
    description: 'Production-ready SaaS application with auth, billing, dashboard, and multi-tenancy.',
    icon: '💎',
    color: '#A78BFA',
    category: 'Development',
    setupTime: '~4 min',
    audience: 'Indie hackers, SaaS founders',
    features: ['Auth & billing sprints', 'Multi-tenant docs', 'Stripe tasks', 'Landing page tasks', '6 sprints'],
    planningItems: [
      { title: 'Vision', content: '## Vision\nLaunch a profitable SaaS product.', order: 0 },
      { title: 'Revenue Model', content: '## Pricing\n- Free tier\n- Pro: $29/mo\n- Team: $99/mo', order: 1 },
      { title: 'Architecture', content: '## Stack\n- Next.js 14 (App Router)\n- Prisma + PostgreSQL\n- Stripe Billing\n- Clerk Auth', order: 2 },
    ],
    sprintNames: ['Project Setup', 'Auth & Onboarding', 'Core Product', 'Billing & Plans', 'Dashboard & Analytics', 'Launch'],
    labels: ['auth', 'billing', 'dashboard', 'landing', 'api', 'database', 'email', 'admin'],
    defaultDocs: [
      { title: 'Architecture Overview', content: '# Architecture\n\nNext.js App Router + Prisma ORM + PostgreSQL + Stripe + Clerk.' },
      { title: 'Stripe Integration Guide', content: '# Stripe Setup\n\n1. Create products in Stripe dashboard\n2. Set webhook endpoint to `/api/webhooks/stripe`\n3. Handle `checkout.session.completed` event' },
    ],
    sampleTasks: [
      { title: 'Configure Clerk Auth', status: 'backlog', priority: 'critical', labels: ['auth'], storyPoints: 3, description: 'Set up Clerk with email + OAuth providers', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Database schema with Prisma', status: 'backlog', priority: 'high', labels: ['database'], storyPoints: 5, description: 'Define User, Organization, Subscription models', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Stripe checkout flow', status: 'backlog', priority: 'high', labels: ['billing'], storyPoints: 8, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Landing page with hero section', status: 'backlog', priority: 'medium', labels: ['landing'], storyPoints: 5, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Admin dashboard', status: 'backlog', priority: 'medium', labels: ['dashboard', 'admin'], storyPoints: 8, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
    ],
  },
  {
    id: 'python-api',
    name: 'Python REST API',
    description: 'FastAPI or Django REST Framework backend with PostgreSQL, authentication, and deployment.',
    icon: '🐍',
    color: '#4ADE80',
    category: 'Development',
    setupTime: '~2 min',
    audience: 'Backend developers',
    features: ['FastAPI / Django setup', '4 sprints', 'API docs', 'Auth tasks', 'Docker deployment'],
    planningItems: [
      { title: 'API Design', content: '## Endpoints\n- `GET /api/v1/users`\n- `POST /api/v1/auth/token`', order: 0 },
    ],
    sprintNames: ['Setup & Auth', 'Core Endpoints', 'Testing & Docs', 'Deployment'],
    labels: ['python', 'api', 'auth', 'database', 'testing', 'docker'],
    defaultDocs: [
      { title: 'API Reference', content: '# API Reference\n\nBase URL: `https://api.yourdomain.com/v1`\n\nAll endpoints require `Authorization: Bearer <token>`' },
    ],
    sampleTasks: [
      { title: 'Initialize FastAPI project', status: 'backlog', priority: 'high', labels: ['python'], storyPoints: 2, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'JWT auth with OAuth2PasswordBearer', status: 'backlog', priority: 'critical', labels: ['auth'], storyPoints: 5, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'PostgreSQL with SQLAlchemy ORM', status: 'backlog', priority: 'high', labels: ['database'], storyPoints: 3, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Pytest test suite', status: 'backlog', priority: 'medium', labels: ['testing'], storyPoints: 5, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
    ],
    defaultSnippets: [
      { title: 'FastAPI Main', language: 'python', description: 'FastAPI app entry point', tags: ['fastapi', 'python'], code: `from fastapi import FastAPI\nfrom fastapi.middleware.cors import CORSMiddleware\n\napp = FastAPI(title="My API", version="1.0.0")\n\napp.add_middleware(\n    CORSMiddleware,\n    allow_origins=["*"],\n    allow_methods=["*"],\n    allow_headers=["*"],\n)\n\n@app.get("/health")\ndef health(): return {"status": "ok"}` },
    ],
  },
  {
    id: 'mobile-app',
    name: 'React Native App',
    description: 'Cross-platform mobile app for iOS and Android using React Native + Expo.',
    icon: '📱',
    color: '#FB923C',
    category: 'Development',
    setupTime: '~3 min',
    audience: 'Mobile developers',
    features: ['Expo setup', 'Navigation sprints', 'Push notifications tasks', 'App store tasks', '5 sprints'],
    planningItems: [
      { title: 'App Architecture', content: '## Stack\n- React Native + Expo\n- React Navigation\n- Zustand state\n- Supabase backend', order: 0 },
    ],
    sprintNames: ['Setup & Navigation', 'Core Screens', 'Notifications & Deep Links', 'Performance', 'App Store Submission'],
    labels: ['mobile', 'ios', 'android', 'navigation', 'notifications', 'performance'],
    defaultDocs: [
      { title: 'App Architecture', content: '# React Native Architecture\n\nUsing Expo managed workflow with EAS Build for distribution.' },
    ],
    sampleTasks: [
      { title: 'Initialize Expo project', status: 'backlog', priority: 'high', labels: ['mobile'], storyPoints: 1, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Set up React Navigation stack', status: 'backlog', priority: 'high', labels: ['navigation'], storyPoints: 3, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Configure push notifications (Expo)', status: 'backlog', priority: 'medium', labels: ['notifications'], storyPoints: 3, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
    ],
  },

  // ── AI & ML ─────────────────────────────────────────────────────────────────
  {
    id: 'ml-pipeline',
    name: 'ML Pipeline',
    description: 'End-to-end machine learning pipeline: data ingestion, feature engineering, training, evaluation, and deployment.',
    icon: '🤖',
    color: '#F472B6',
    category: 'AI & ML',
    setupTime: '~4 min',
    audience: 'Data scientists, ML engineers',
    features: ['5 ML phases', 'Experiment tracking', 'Model docs', 'MLOps tasks', 'Jupyter notebooks'],
    planningItems: [
      { title: 'Problem Definition', content: '## Problem\n- Type: Classification / Regression / Clustering\n- Target metric: Accuracy / F1 / RMSE\n- Baseline model:', order: 0 },
      { title: 'Data Sources', content: '## Data\n- Source:\n- Format:\n- Size:\n- Privacy level:', order: 1 },
    ],
    sprintNames: ['Data Collection', 'EDA & Feature Engineering', 'Model Training', 'Evaluation & Tuning', 'MLOps & Deployment'],
    labels: ['data', 'eda', 'feature-engineering', 'training', 'evaluation', 'deployment', 'mlops'],
    defaultDocs: [
      { title: 'Experiment Log', content: '# Experiment Log\n\n| Run | Model | Params | Accuracy | Notes |\n|-----|-------|--------|----------|-------|\n| 1 | Baseline | - | - | - |' },
      { title: 'Model Card', content: '# Model Card\n\n## Overview\n- **Model type**:\n- **Task**:\n- **Training data**:\n- **Limitations**:' },
    ],
    sampleTasks: [
      { title: 'Data collection & ingestion pipeline', status: 'backlog', priority: 'high', labels: ['data'], storyPoints: 5, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Exploratory data analysis (EDA)', status: 'backlog', priority: 'high', labels: ['eda'], storyPoints: 5, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Feature engineering & preprocessing', status: 'backlog', priority: 'high', labels: ['feature-engineering'], storyPoints: 8, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Train baseline model', status: 'backlog', priority: 'high', labels: ['training'], storyPoints: 5, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Hyperparameter tuning', status: 'backlog', priority: 'medium', labels: ['training', 'evaluation'], storyPoints: 5, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Deploy model with FastAPI', status: 'backlog', priority: 'medium', labels: ['deployment', 'mlops'], storyPoints: 8, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
    ],
  },
  {
    id: 'llm-product',
    name: 'LLM Application',
    description: 'AI-powered product built on top of GPT-4, Claude, or Gemini with RAG, streaming, and evaluation.',
    icon: '🧠',
    color: '#818CF8',
    category: 'AI & ML',
    setupTime: '~3 min',
    audience: 'AI product builders',
    features: ['RAG pipeline tasks', 'Prompt library', 'Evaluation framework', 'API integration', '5 sprints'],
    planningItems: [
      { title: 'Vision', content: '## Vision\nBuild an LLM-powered product that saves users significant time.', order: 0 },
      { title: 'Model Selection', content: '## Models\n- Primary: GPT-4o / Claude 3.5 / Gemini 1.5\n- Embedding: text-embedding-3-small\n- Vector DB: Pinecone / Chroma', order: 1 },
    ],
    sprintNames: ['Architecture & API Setup', 'Prompt Engineering', 'RAG Pipeline', 'UI & UX', 'Evals & Launch'],
    labels: ['llm', 'rag', 'prompts', 'embeddings', 'streaming', 'eval'],
    defaultDocs: [
      { title: 'Prompt Library', content: '# Prompt Library\n\n## System Prompts\n\n### Assistant Prompt\n```\nYou are a helpful assistant...\n```' },
      { title: 'RAG Architecture', content: '# RAG Architecture\n\n1. **Ingestion**: Chunk docs → embed → store in vector DB\n2. **Retrieval**: Embed query → similarity search → top-k docs\n3. **Generation**: Build prompt with context → stream response' },
    ],
    sampleTasks: [
      { title: 'OpenAI SDK setup + streaming', status: 'backlog', priority: 'high', labels: ['llm'], storyPoints: 2, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Document ingestion pipeline', status: 'backlog', priority: 'high', labels: ['rag', 'embeddings'], storyPoints: 8, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Vector database setup (Pinecone)', status: 'backlog', priority: 'high', labels: ['rag'], storyPoints: 5, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Prompt template system', status: 'backlog', priority: 'medium', labels: ['prompts'], storyPoints: 3, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'LLM evaluation framework', status: 'backlog', priority: 'medium', labels: ['eval'], storyPoints: 5, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
    ],
    defaultSnippets: [
      { title: 'OpenAI Streaming', language: 'typescript', description: 'Stream chat completion from OpenAI', tags: ['openai', 'streaming'], code: `import OpenAI from 'openai';\n\nconst client = new OpenAI();\n\nasync function streamChat(messages: OpenAI.Chat.ChatCompletionMessageParam[]) {\n  const stream = await client.chat.completions.create({\n    model: 'gpt-4o',\n    messages,\n    stream: true,\n  });\n  for await (const chunk of stream) {\n    process.stdout.write(chunk.choices[0]?.delta?.content ?? '');\n  }\n}` },
    ],
  },

  // ── STARTUP ──────────────────────────────────────────────────────────────────
  {
    id: 'mvp-launch',
    name: 'MVP Launch',
    description: 'Zero-to-launch plan for a startup MVP in 6 weeks with lean validation, build, and growth phases.',
    icon: '🚀',
    color: '#F06277',
    category: 'Startup',
    setupTime: '~3 min',
    audience: 'Founders, indie hackers',
    features: ['6 week plan', 'Validation tasks', 'GTM strategy', 'Growth experiments', 'OKR tracking'],
    planningItems: [
      { title: 'Problem Statement', content: '## Problem\n**Who**: \n**Pain**: \n**Current solution**: \n**Our approach**: ', order: 0 },
      { title: 'OKRs', content: '## Q1 OKRs\n**Objective**: Launch MVP and validate product-market fit\n\n**KR1**: 100 sign-ups in first month\n**KR2**: 30% D7 retention\n**KR3**: $1k MRR', order: 1 },
      { title: 'GTM Strategy', content: '## Go-To-Market\n\n### Channels\n- Product Hunt launch\n- Twitter/X audience\n- Niche communities (Reddit, Discord)\n\n### Messaging\nTagline: ', order: 2 },
    ],
    sprintNames: ['Validate & Research', 'Build Core', 'Internal Alpha', 'Beta Launch', 'Growth & Iterate', 'Scale'],
    labels: ['validation', 'core', 'gtm', 'growth', 'retention', 'analytics'],
    defaultDocs: [
      { title: 'Lean Canvas', content: '# Lean Canvas\n\n| Problem | Solution | Unique Value Prop |\n|---------|----------|-------------------|\n| | | |\n\n| Customer Segments | Channels | Revenue Streams |\n|-------------------|----------|------------------|\n| | | |' },
      { title: 'User Research Notes', content: '# User Research\n\n## Interviews\n\n### Interview 1\n- **Name**:\n- **Role**:\n- **Key insights**:' },
    ],
    sampleTasks: [
      { title: '10 user discovery interviews', status: 'backlog', priority: 'critical', labels: ['validation'], storyPoints: 5, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Build core feature v1', status: 'backlog', priority: 'high', labels: ['core'], storyPoints: 13, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Analytics & funnel tracking', status: 'backlog', priority: 'high', labels: ['analytics'], storyPoints: 3, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Product Hunt launch assets', status: 'backlog', priority: 'medium', labels: ['gtm'], storyPoints: 5, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Email drip sequence (onboarding)', status: 'backlog', priority: 'medium', labels: ['retention'], storyPoints: 5, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'A/B test landing page headline', status: 'backlog', priority: 'low', labels: ['growth'], storyPoints: 3, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
    ],
  },
  {
    id: 'product-roadmap',
    name: 'Product Roadmap',
    description: 'Strategic product planning with roadmap, PRDs, feature prioritization, and stakeholder docs.',
    icon: '🗺️',
    color: '#FACC15',
    category: 'Startup',
    setupTime: '~2 min',
    audience: 'Product managers',
    features: ['Quarterly roadmap', 'PRD templates', 'Feature scoring', 'Stakeholder updates', '4 quarters'],
    planningItems: [
      { title: 'Product Vision', content: '## Product Vision\n\nIn 3 years, [Product] will be...', order: 0 },
      { title: 'Now / Next / Later', content: '## Now\n- \n\n## Next\n- \n\n## Later\n- ', order: 1 },
    ],
    sprintNames: ['Q1 — Foundation', 'Q2 — Growth', 'Q3 — Scale', 'Q4 — Optimize'],
    labels: ['prd', 'research', 'design', 'engineering', 'stakeholder', 'metrics'],
    defaultDocs: [
      { title: 'Product Requirements Doc (PRD)', content: '# PRD Template\n\n## Problem Statement\n\n## Goals\n\n## Non-Goals\n\n## User Stories\n\n## Success Metrics' },
      { title: 'Feature Prioritization Matrix', content: '# Feature Scoring\n\n| Feature | Impact | Effort | Score |\n|---------|--------|--------|-------|\n| | High | Low | 9 |' },
    ],
    sampleTasks: [
      { title: 'Quarterly OKR planning session', status: 'backlog', priority: 'high', labels: ['metrics'], storyPoints: 3, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Write PRDs for top 3 features', status: 'backlog', priority: 'high', labels: ['prd'], storyPoints: 8, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'User research synthesis', status: 'backlog', priority: 'medium', labels: ['research'], storyPoints: 5, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
    ],
  },

  // ── ENTERPRISE ───────────────────────────────────────────────────────────────
  {
    id: 'enterprise-platform',
    name: 'Enterprise Platform',
    description: 'Large-scale enterprise application with SSO, RBAC, audit logging, compliance, and SLA docs.',
    icon: '🏗️',
    color: '#6B7280',
    category: 'Enterprise',
    setupTime: '~5 min',
    audience: 'Enterprise engineering teams',
    features: ['SSO & RBAC', 'Compliance docs', 'SLA templates', 'Audit logging', '8 sprints'],
    planningItems: [
      { title: 'Architecture Decision Records', content: '# ADRs\n\n## ADR-001: Authentication\n**Status**: Accepted\n**Decision**: Use SAML 2.0 SSO', order: 0 },
      { title: 'Security & Compliance', content: '# Security\n\n- SOC 2 Type II controls\n- GDPR data mapping\n- Pen test schedule', order: 1 },
    ],
    sprintNames: ['Discovery & Architecture', 'Auth & SSO', 'Core Platform', 'RBAC & Permissions', 'Integrations', 'Performance', 'Security Audit', 'Launch'],
    labels: ['auth', 'rbac', 'compliance', 'security', 'integration', 'performance', 'audit', 'sla'],
    defaultDocs: [
      { title: 'SLA Definition', content: '# Service Level Agreement\n\n- **Uptime**: 99.9%\n- **RTO**: 4 hours\n- **RPO**: 1 hour' },
      { title: 'Security Runbook', content: '# Security Runbook\n\n## Incident Response\n1. Detect\n2. Contain\n3. Eradicate\n4. Recover\n5. Post-mortem' },
    ],
    sampleTasks: [
      { title: 'SAML 2.0 SSO integration', status: 'backlog', priority: 'critical', labels: ['auth'], storyPoints: 13, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'RBAC system with role hierarchy', status: 'backlog', priority: 'high', labels: ['rbac'], storyPoints: 8, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Audit logging system', status: 'backlog', priority: 'high', labels: ['audit'], storyPoints: 5, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'GDPR compliance review', status: 'backlog', priority: 'high', labels: ['compliance'], storyPoints: 8, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
    ],
  },

  // ── DESIGN ───────────────────────────────────────────────────────────────────
  {
    id: 'design-system',
    name: 'Design System',
    description: 'Complete design system with component library, tokens, Storybook, and accessibility guidelines.',
    icon: '🎨',
    color: '#F472B6',
    category: 'Design',
    setupTime: '~3 min',
    audience: 'Design & frontend teams',
    features: ['Token system', 'Storybook setup', 'Accessibility docs', 'Component library', '5 sprints'],
    planningItems: [
      { title: 'Design Principles', content: '## Principles\n1. Clarity\n2. Consistency\n3. Delight\n4. Accessibility', order: 0 },
      { title: 'Token Architecture', content: '## Tokens\n- Primitive tokens (colors, spacing)\n- Semantic tokens (--color-primary)\n- Component tokens', order: 1 },
    ],
    sprintNames: ['Foundation & Tokens', 'Core Components', 'Complex Components', 'Storybook & Docs', 'Accessibility Audit'],
    labels: ['tokens', 'components', 'storybook', 'a11y', 'typography', 'icons'],
    defaultDocs: [
      { title: 'Color System', content: '# Color System\n\n## Brand Colors\n- Primary: #\n- Secondary: #\n\n## Semantic Colors\n- Success: #\n- Error: #\n- Warning: #' },
      { title: 'Component Checklist', content: '# Component Checklist\n\nBefore shipping a component:\n- [ ] Variants documented\n- [ ] Keyboard accessible\n- [ ] Screen reader tested\n- [ ] Storybook stories added' },
    ],
    sampleTasks: [
      { title: 'Define design token system', status: 'backlog', priority: 'critical', labels: ['tokens'], storyPoints: 5, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Build Button component (all variants)', status: 'backlog', priority: 'high', labels: ['components'], storyPoints: 3, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Set up Storybook 8', status: 'backlog', priority: 'high', labels: ['storybook'], storyPoints: 3, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'WCAG 2.1 AA audit', status: 'backlog', priority: 'medium', labels: ['a11y'], storyPoints: 8, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
    ],
  },
  {
    id: 'product-redesign',
    name: 'Product Redesign',
    description: 'Full UX/UI redesign sprint with user research, wireframes, prototypes, and handoff to engineering.',
    icon: '✏️',
    color: '#C084FC',
    category: 'Design',
    setupTime: '~2 min',
    audience: 'UX/UI designers, product teams',
    features: ['Research phase', 'Wireframing sprints', 'User testing tasks', 'Figma handoff', '4 sprints'],
    planningItems: [
      { title: 'Design Brief', content: '## Design Brief\n\n**Project**: \n**Goals**: \n**Timeline**: \n**Stakeholders**: ', order: 0 },
    ],
    sprintNames: ['User Research', 'Wireframes & Information Architecture', 'High-Fidelity Design', 'Prototype & Test'],
    labels: ['research', 'wireframes', 'ui', 'prototype', 'testing', 'handoff'],
    defaultDocs: [
      { title: 'UX Research Plan', content: '# UX Research Plan\n\n## Methods\n- Usability testing (5 participants)\n- Card sorting\n- A/B testing\n\n## Key questions\n1. \n2. ' },
    ],
    sampleTasks: [
      { title: '5 usability testing sessions', status: 'backlog', priority: 'high', labels: ['research', 'testing'], storyPoints: 5, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Competitive analysis (10 products)', status: 'backlog', priority: 'high', labels: ['research'], storyPoints: 3, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Mobile wireframes (30 screens)', status: 'backlog', priority: 'high', labels: ['wireframes'], storyPoints: 8, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Interactive Figma prototype', status: 'backlog', priority: 'medium', labels: ['prototype'], storyPoints: 5, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
    ],
  },

  // ── EDUCATION ────────────────────────────────────────────────────────────────
  {
    id: 'online-course',
    name: 'Online Course',
    description: 'Plan, produce, and launch an online course with curriculum design, video production, and marketing.',
    icon: '📚',
    color: '#34D399',
    category: 'Education',
    setupTime: '~2 min',
    audience: 'Course creators, educators',
    features: ['Curriculum planning', 'Production sprints', 'Launch tasks', 'Student feedback', '4 sprints'],
    planningItems: [
      { title: 'Course Outline', content: '## Course Outline\n\n### Module 1: \n- Lesson 1:\n- Lesson 2:\n\n### Module 2:', order: 0 },
    ],
    sprintNames: ['Curriculum Design', 'Video Production', 'Platform Setup', 'Launch & Marketing'],
    labels: ['curriculum', 'video', 'platform', 'marketing', 'students', 'feedback'],
    defaultDocs: [
      { title: 'Curriculum Map', content: '# Curriculum Map\n\n| Module | Title | Duration | Outcomes |\n|--------|-------|----------|----------|\n| 1 | | | |' },
    ],
    sampleTasks: [
      { title: 'Define learning outcomes per module', status: 'backlog', priority: 'high', labels: ['curriculum'], storyPoints: 3, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Record 10 lesson videos', status: 'backlog', priority: 'high', labels: ['video'], storyPoints: 13, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Upload to Teachable / Gumroad', status: 'backlog', priority: 'medium', labels: ['platform'], storyPoints: 3, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Email launch sequence (7 emails)', status: 'backlog', priority: 'medium', labels: ['marketing'], storyPoints: 5, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
    ],
  },

  // ── OPEN SOURCE ──────────────────────────────────────────────────────────────
  {
    id: 'open-source-lib',
    name: 'Open Source Library',
    description: 'Build and release an open source library with documentation site, CI/CD, and community guidelines.',
    icon: '📦',
    color: '#F59E0B',
    category: 'Open Source',
    setupTime: '~3 min',
    audience: 'OSS maintainers, library authors',
    features: ['npm publish pipeline', 'Docs site', 'Contributing guide', 'Semver tasks', '5 sprints'],
    planningItems: [
      { title: 'Library Scope', content: '## What This Library Does\n\n- Primary use case:\n- Target environment: Node.js / Browser / Both\n- Key APIs:', order: 0 },
      { title: 'Community Guidelines', content: '## Community\n\n- Code of Conduct: Contributor Covenant\n- Issue templates\n- PR template', order: 1 },
    ],
    sprintNames: ['API Design', 'Core Implementation', 'Testing & Edge Cases', 'Documentation Site', 'v1.0 Release'],
    labels: ['api', 'core', 'testing', 'docs', 'release', 'community'],
    defaultDocs: [
      { title: 'API Reference', content: '# API Reference\n\n## Installation\n```bash\nnpm install my-lib\n```\n\n## Usage\n```js\nimport { myLib } from "my-lib";\n```' },
      { title: 'Contributing Guide', content: '# Contributing\n\n1. Fork the repo\n2. Create your feature branch\n3. Run tests: `npm test`\n4. Submit a PR' },
    ],
    sampleTasks: [
      { title: 'Design public API surface', status: 'backlog', priority: 'critical', labels: ['api'], storyPoints: 5, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'TypeScript typings + JSDoc', status: 'backlog', priority: 'high', labels: ['core'], storyPoints: 5, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: '100% test coverage', status: 'backlog', priority: 'high', labels: ['testing'], storyPoints: 8, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Docusaurus documentation site', status: 'backlog', priority: 'medium', labels: ['docs'], storyPoints: 8, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Automated npm publish with GitHub Actions', status: 'backlog', priority: 'medium', labels: ['release'], storyPoints: 3, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
    ],
    defaultSnippets: [
      { title: 'GitHub Actions Release', language: 'yaml', description: 'Auto-publish to npm on tag push', tags: ['ci', 'npm'], code: `name: Release\non:\n  push:\n    tags: ['v*']\njobs:\n  publish:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 20\n          registry-url: 'https://registry.npmjs.org'\n      - run: npm ci\n      - run: npm test\n      - run: npm publish\n        env:\n          NODE_AUTH_TOKEN: \${{ secrets.NPM_TOKEN }}` },
    ],
  },

  // ── PERSONAL ──────────────────────────────────────────────────────────────────
  {
    id: 'personal-portfolio',
    name: 'Personal Portfolio',
    description: 'Build a stunning developer portfolio with projects showcase, blog, and contact form.',
    icon: '🌟',
    color: '#818CF8',
    category: 'Personal',
    setupTime: '~2 min',
    audience: 'Developers, designers',
    features: ['Portfolio design sprints', 'Blog setup', 'SEO optimization', 'Domain setup', '3 sprints'],
    planningItems: [
      { title: 'Content Plan', content: '## Sections\n- Hero\n- About\n- Projects (6)\n- Skills\n- Blog\n- Contact', order: 0 },
    ],
    sprintNames: ['Design & Structure', 'Content & Projects', 'SEO & Launch'],
    labels: ['design', 'content', 'seo', 'blog', 'projects', 'performance'],
    defaultDocs: [
      { title: 'Project Showcase List', content: '# Projects to Showcase\n\n| Project | Description | Tech Stack | Link |\n|---------|-------------|------------|------|\n| | | | |' },
    ],
    sampleTasks: [
      { title: 'Design hero section with animations', status: 'backlog', priority: 'high', labels: ['design'], storyPoints: 5, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Write 3 case study pages', status: 'backlog', priority: 'high', labels: ['content', 'projects'], storyPoints: 8, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'SEO + meta tags + sitemap', status: 'backlog', priority: 'medium', labels: ['seo'], storyPoints: 3, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Performance audit (Lighthouse 90+)', status: 'backlog', priority: 'medium', labels: ['performance'], storyPoints: 3, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
    ],
  },
  {
    id: 'side-project',
    name: 'Side Project',
    description: 'Lightweight personal project tracking with minimal overhead — just enough structure to ship.',
    icon: '🔥',
    color: '#F06277',
    category: 'Personal',
    setupTime: '~1 min',
    audience: 'Solo developers',
    features: ['Minimal process', '2 sprints', 'Ship fast', 'One page planning', 'Idea tracking'],
    planningItems: [
      { title: 'One-Page Plan', content: '## What am I building?\n\n**Problem**: \n**Solution**: \n**Target user**: \n**First version (MVP)**: \n**Definition of done**: ', order: 0 },
    ],
    sprintNames: ['Build', 'Launch'],
    labels: ['core', 'ui', 'launch', 'bug', 'idea'],
    defaultDocs: [
      { title: 'Quick Notes', content: '# Notes\n\n## Ideas\n-\n\n## Bugs\n-\n\n## Backlog\n-' },
    ],
    sampleTasks: [
      { title: 'Define MVP scope (3 features max)', status: 'backlog', priority: 'critical', labels: ['core'], storyPoints: 1, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Build and deploy v0.1', status: 'backlog', priority: 'high', labels: ['core'], storyPoints: 8, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
      { title: 'Get first 10 users', status: 'backlog', priority: 'high', labels: ['launch'], storyPoints: 3, description: '', acceptanceCriteria: '', assignee: '', isFavorite: false },
    ],
  },

  // ── BLANK ────────────────────────────────────────────────────────────────────
  {
    id: 'blank',
    name: 'Blank Project',
    description: 'Start from scratch with an empty workspace. Fully customizable.',
    icon: '✨',
    color: '#9CA3AF',
    category: 'Personal',
    setupTime: '< 1 min',
    audience: 'Everyone',
    features: ['Empty board', 'Default planning sections', 'No pre-built tasks'],
    planningItems: [],
    sprintNames: [],
    labels: [],
    defaultDocs: [],
    sampleTasks: [],
  },
];

export const BLUEPRINT_CATEGORIES = [
  'All',
  'Development',
  'AI & ML',
  'Startup',
  'Enterprise',
  'Design',
  'Education',
  'Open Source',
  'Personal',
  'Custom',
] as const;
